[application]
name = "Mango³ Store"

[web.app]
title = "Mango³ Store"

[web.watcher]
reload_html = true

[bundle]
identifier = "app.mango3.store"
icon = ["app/assets/favicon.png"]
publisher = "Mango³ Group"
copyright = "© 2025 Mango³ Group"
