name: Analysis

on:
    workflow_call:

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://mango3:mango3@127.0.0.1:5432/store_test

jobs:
    check_rust:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_USER: mango3
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_DB: store_test
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-dioxus
            - name: Check with cargo-clippy
              run: |
                  cargo clippy --package store-core --all-features -- -D warnings || failed
                  cargo clippy --package store-app -- -D warnings
                  cargo clippy --package store-app --no-default-features --features desktop -- -D warnings || failed
                  cargo clippy --package store-app --no-default-features --features mobile -- -D warnings || failed
                  cargo clippy --package store-app --no-default-features --features server -- -D warnings || failed
                  # cargo clippy --package store-api -- -D warnings || failed
                  # cargo clippy --package store-cli --all-features -- -D warnings || failed
            - name: Check with cargo-fmt
              run: cargo fmt --all --check
            - name: Check with dioxus-cli
              run: |
                  dx check --package store-app --all-features
                  dx fmt --package store-app --check

    check_sql:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: quarylabs/install-sqruff-cli-action@main
            - name: Check with sqruff
              run: sqruff lint migrations/*.sql
